### PR TITLE
fix leaking file descriptor in fault_syscall if couldn't find syscall number

### PR DESCRIPTION
**Pull request by dmur1**
note this doesn't address the suggested todo to avoid opening this file over and over and in fixing this a neater solution could perhaps be found

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks! I'll review in a bit.

**Comment by dmur1** [comment]
looking at the linter it appears that trying to install clang-format-7 fails - most modern version appears to be 12 so maybe updating that requirement might make the linter happy :)

**Comment by woodruffw** [comment]
> looking at the linter it appears that trying to install clang-format-7 fails - most modern version appears to be 12 so maybe updating that requirement might make the linter happy :)

Yep. I just fixed that on `master`, so a rebase should address it here.

**Review by woodruffw — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
